# Generated by Django 6.0.5 on 2026-05-29 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_titular', models.CharField(max_length=100, verbose_name='Nombre del Titular')),
                ('apellido_titular', models.CharField(max_length=100, verbose_name='Apellido del Titular')),
                ('dni_titular', models.CharField(max_length=15, verbose_name='DNI del Titular')),
                ('fecha_nac_titular', models.DateField(verbose_name='Fecha de Nacimiento (Titular)')),
                ('email_titular', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('tel_titular', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('ingreso_titular', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Ingreso Neto (Titular)')),
                ('nombre_garante', models.CharField(max_length=100, verbose_name='Nombre del Garante')),
                ('apellido_garante', models.CharField(max_length=100, verbose_name='Apellido del Garante')),
                ('dni_garante', models.CharField(max_length=15, verbose_name='DNI del Garante')),
                ('fecha_nac_garante', models.DateField(verbose_name='Fecha de Nacimiento (Garante)')),
                ('condicion_laboral_garante', models.CharField(choices=[('dependiente', 'Dependiente'), ('independiente', 'Independiente')], max_length=20, verbose_name='Condición Laboral')),
                ('antiguedad_laboral_garante', models.PositiveIntegerField(verbose_name='Antigüedad Laboral (años)')),
                ('ingreso_garante', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Ingreso Neto (Garante)')),
                ('modelo_auto', models.CharField(choices=[('gol', 'Volkswagen Gol Trend'), ('tracker', 'Chevrolet Tracker'), ('corolla', 'Toyota Corolla Cross'), ('a6', 'Audi A6')], max_length=20, verbose_name='Modelo Elegido')),
                ('tipo_plan', models.CharField(choices=[('70', 'Plan 70/30'), ('80', 'Plan 80/20')], max_length=2, verbose_name='Tipo de Plan')),
                ('cantidad_cuotas', models.IntegerField(choices=[(72, '72 cuotas'), (84, '84 cuotas'), (120, '120 cuotas')], verbose_name='Cantidad de Cuotas')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Solicitud')),
            ],
            options={
                'verbose_name': 'Solicitud de Simulación',
                'verbose_name_plural': 'Solicitudes de Simulación',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
